### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by alexbizeau** [a2flo/floor#3]
I download latest source code and I followed the instructions to compile on Windows.

Im facing tons of ambiguous error inside **floor\constexpr\const_math.hpp**, such as

> E:\floor_cpp\floor\constexpr\const_math.hpp(582,6): error : call to 'isinf' is ambiguous
>                   if(isinf(val) && val > (fp_type)0) {

Is there something Im missing?

On a side note, it there a way to compile this as a static library on Windows? When I look to the logs (not familiar with ninja), it seems to try to build a .dll only

I join the full build error logs
[floor_build_error.txt](https://github.com/a2flo/floor/files/5705170/floor_build_error.txt)

**Comment by a2flo** [comment]
Fixed with 0d60ca0cc37357c8d39dba88da8a09f53be5e3ae.
MS added some non-standard fp template functions that collided with the functions in const_math ...

The CMake build path can only create dynamic libs right now (and considering how incredibly slow static linking on Windows is, this is a good thing). If you really want a static library, you need to go the MSYS2/MinGW + build.sh path ("./build.sh static libstdc++"). But no guarantees that this will actually work on Windows (right now, I'm getting a lot of compiler crashes).
